#!/usr/bin/env fish

# Symlink everything

# Dotfiles
ln -sfFn ../.hammerspoon/ ~/.hammerspoon
ln -sfFn ../.proton ~/.proton
ln -sfFn ../.wgetrc/ ~/.wgetrc
ln -sfFn ../fish/ ~/.config/fish
ln -sfFn ../karabiner/ ~/.config/karabiner
ln -sfFn ../scripts/ ~/scripts

# Home dir
ln -sfFn ~/Documents/.hidden/.config ~/.config
ln -sfFn ~/Documents/.hidden/Google\ Drive/* ~/Documents
ln -sfFn ~/Documents/.hidden/Home/* ~/
ln -sfFn ~/Documents/.hidden/localshare ~/.local/share

# Library
ln -sfFn ~/Documents/.hidden/Library/Application\ Support/* ~/Library/Application\ Support/
ln -sfFn ~/Documents/.hidden/Library/Containers/* ~/Library/Containers/
ln -sfFn ~/Documents/.hidden/Library/Preferences/* ~/Library/Preferences/