#!/usr/bin/env fish

# Symlink everything

# Home dir
ln -sfFn ~/Documents/.hidden/.config ~/.config
ln -sfFn ~/Documents/.hidden/Google\ Drive/* ~/Documents
ln -sfFn ~/Documents/.hidden/Home/* ~/
ln -sfFn ~/Documents/.hidden/localshare ~/.local/share

# Library
ln -sfFn ~/Documents/.hidden/Library/Application\ Support/* ~/Library/Application\ Support/
ln -sfFn ~/Documents/.hidden/Library/Containers/* ~/Library/Containers/
ln -sfFn ~/Documents/.hidden/Library/Preferences/* ~/Library/Preferences/
